import type { FontMetadata, ResolvedOptions } from '../types.ts'

/** 生成类型安全的自产 TS 入口(IconName 联合 + codepoints + iconClass)。 */
export function emitDts(metadata: FontMetadata, o: ResolvedOptions): string {
  const glyphs = metadata.glyphs
  const q = (s: string) => JSON.stringify(s)
  const hex = (n: number) => '0x' + n.toString(16)

  const union = glyphs.length
    ? glyphs.map((g) => `  | ${q(g.name)}`).join('\n')
    : '  | never'

  const cp = glyphs.map((g) => `  ${q(g.name)}: ${hex(g.codepoint)},`).join('\n')
  const cls = glyphs.map((g) => `  ${q(g.name)}: ${q(o.classPrefix + g.name)},`).join('\n')
  const colorList = glyphs
    .filter((g) => g.color)
    .map((g) => q(g.name))
    .join(', ')

  return `// AUTO-GENERATED by @colorfont/core. DO NOT EDIT.

export type IconName =
${union};

export const codepoints = {
${cp}
} as const satisfies Record<IconName, number>;

export const iconClass = {
${cls}
} as const satisfies Record<IconName, string>;

export const baseClass = ${q(o.baseSelector.replace(/^\./, ''))};

/** 多色图标(在支持 COLR/OT-SVG 的浏览器彩色渲染)。 */
export const colorIcons = [${colorList}] as const;

export function iconContent(name: IconName): string {
  return String.fromCodePoint(codepoints[name]);
}
`
}
